### ISSUE TITLE
US2 - If is_anon is true, then change text of username to "Anonymous" on post.

### ISSUE THREAD

**Issue by kswim8** [CMU-313/spring23-nodebb-team-dj-kew#3]
Users that post anonymously should have the username associated with the post be "Anonymous" instead of their actual username.

Effort: Medium
Depends on: #1 
Milestone: Sprint 1
Acceptance Criteria: Pass visual test, and tests that ensure that the text of the name associated with a post is "Anonymous" when is_anon is true.

**Comment by dennischenjr** [comment]
#31
